if __name__ == "__main__":
    from julia import QuadraticMap
    mandelbrot = QuadraticMap()
    im = mandelbrot.draw_mandelbrot(res_x=1440, res_y=1440, x_range=(-2, 2), y_range=(-2, 2), multiprocessing=True)
    im.show()
    mandelbrot.c = complex(0.392, -0.167)
    close_to_edge1 = mandelbrot.draw_julia(res_x=1440, res_y=1440, x_range=(-2, 2), y_range=(-2, 2), multiprocessing=True)
    close_to_edge1.show()
    mandelbrot.c = complex(-0.1, 0.95)
    close_to_edge2 = mandelbrot.draw_julia(res_x=1440, res_y=1440, x_range=(-2, 2), y_range=(-2, 2), multiprocessing=True)
    close_to_edge2.show()
    mandelbrot.c = complex(-0.892, 0)
    interior = mandelbrot.draw_julia(res_x=1440, res_y=1440, x_range=(-2, 2), y_range=(-2, 2), multiprocessing=True)
    interior.show()
    mandelbrot.c = complex(0.05, 0.733)
    exterior = mandelbrot.draw_julia(res_x=1440, res_y=1440, x_range=(-2, 2), y_range=(-2, 2), multiprocessing=True)
    exterior.show()